import { Context } from 'koishi';
import { PermissionGroup, GroupConfigRecord, GlobalConfigRecord, BlacklistEntry, WhitelistEntry, LogEntry, JoinRequestRecord } from '../types';
export declare function initModels(ctx: Context): void;
export declare class Store {
    private db;
    private log;
    constructor(ctx: Context);
    blacklistAdd(userId: string, source?: BlacklistEntry['source'], groupId?: string): Promise<void>;
    blacklistRemove(userId: string, groupId?: string): Promise<boolean>;
    blacklistList(groupId?: string): Promise<BlacklistEntry[]>;
    blacklistHas(userId: string, groupId?: string, applyGlobal?: boolean): Promise<boolean>;
    blacklistMoveToGlobal(userId: string, groupId: string): Promise<boolean>;
    whitelistAdd(userId: string, groupId?: string, flags?: Partial<Pick<WhitelistEntry, 'exemptReport' | 'exemptJoin' | 'exemptBannedWord'>>): Promise<void>;
    whitelistUpdate(userId: string, groupId: string, patch: Partial<WhitelistEntry>): Promise<void>;
    whitelistRemove(userId: string, groupId?: string): Promise<boolean>;
    whitelistList(groupId?: string): Promise<WhitelistEntry[]>;
    whitelistEntry(userId: string, groupId?: string, applyGlobal?: boolean): Promise<WhitelistEntry | undefined>;
    whitelistMoveToGlobal(userId: string, groupId: string): Promise<boolean>;
    permissionGroups(): Promise<PermissionGroup[]>;
    permissionGroupByName(name: string): Promise<PermissionGroup | undefined>;
    permissionGroupCreate(data: Omit<PermissionGroup, 'id'>): Promise<PermissionGroup>;
    permissionGroupUpdate(id: number, patch: Partial<PermissionGroup>): Promise<void>;
    permissionGroupRemove(id: number): Promise<void>;
    groupConfigGet(groupId: string): Promise<GroupConfigRecord | undefined>;
    groupConfigSet(groupId: string, config: any): Promise<void>;
    groupConfigAll(): Promise<GroupConfigRecord[]>;
    groupConfigRemove(groupId: string): Promise<void>;
    globalConfigGet(): Promise<GlobalConfigRecord | undefined>;
    globalConfigSet(config: any): Promise<void>;
    joinRequestCreate(data: Omit<JoinRequestRecord, 'id'>): Promise<JoinRequestRecord>;
    joinRequestByFlag(flag: string): Promise<JoinRequestRecord | undefined>;
    joinRequestUpdate(flag: string, patch: Partial<JoinRequestRecord>): Promise<void>;
    joinRequestList(status?: string): Promise<JoinRequestRecord[]>;
    joinRequestRemove(flag: string): Promise<void>;
    joinRequestCountRecent(userId: string, groupId: string, since: Date): Promise<number>;
    joinRequestCleanup(): Promise<void>;
    private static readonly MAX_LOG_COUNT;
    logAdd(entry: Omit<LogEntry, 'id' | 'createdAt'>): Promise<void>;
    pruneLogs(): Promise<void>;
    logClear(): Promise<void>;
    logCountRecent(type: string, operatorId: string, groupId: string, since: Date): Promise<number>;
    logQuery(type?: string, limit?: number): Promise<LogEntry[]>;
}
